const TYPE = {
    GET_CARTELERA : "GET_CARTELERA",
    GET_ESTRENO: "GET_ESTRENO",
    GET_POPULAR : "GET_POPULAR",
    GET_TOP_RATED : "GET_TOP_RATED",
    GET_BY_GENERO : "GET_BY_GENERO",
    GET_SEARCH : "GET_SEARCH"
}

export default TYPE;